import type { NextPage } from "next";
import Head from "next/head";
import CitationForm from "../components/CitationForm";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto min-h-screen p-4">
        <h1 className="mb-[-4rem] text-center text-2xl font-bold">
          Citation Generator
        </h1>
        <CitationForm />
        <h2 className="ml-8 text-xl font-bold">Citations</h2>
      </main>
    </>
  );
};

export default Home;
